### ISSUE TITLE
lack code ! 

### ISSUE THREAD

**Issue by M2-Zhang** [jnzhihuoo1/NumGPT#1]
I'm wondering if something is missing from your code? Especially in the model, there is a module called "FusionLayerV2", which is not defined?
<img width="1389" alt="image" src="https://github.com/jnzhihuoo1/NumGPT/assets/39217661/082f7f55-6fc3-4121-b2b5-94129916b58b">
thank you.

**Comment by jnzhihuoo1** [comment]
Sorry for that. I have added this module back.
